/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.AnimalDAO;
import model.dao.ClienteDAO;
import Classes_back.Animal;
import Classes_back.Cliente;

/**
 *
 * @author Admin
 */
public class Cadastro_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_cliente
     */
    public Cadastro_cliente() {
        initComponents();
        this.setTitle("Cadastro de clientes");
        cmb_estado.addItem("AC");
        cmb_estado.addItem("AL");
        cmb_estado.addItem("AP");
        cmb_estado.addItem("AM");
        cmb_estado.addItem("BA");
        cmb_estado.addItem("CE");
        cmb_estado.addItem("DF");
        cmb_estado.addItem("ES");
        cmb_estado.addItem("GO");
        cmb_estado.addItem("MA");
        cmb_estado.addItem("MT");
        cmb_estado.addItem("MS");
        cmb_estado.addItem("MG");
        cmb_estado.addItem("PA");
        cmb_estado.addItem("PB");
        cmb_estado.addItem("PR");
        cmb_estado.addItem("PE");
        cmb_estado.addItem("PI");
        cmb_estado.addItem("RJ");
        cmb_estado.addItem("RN");
        cmb_estado.addItem("RS");
        cmb_estado.addItem("RO");
        cmb_estado.addItem("RR");
        cmb_estado.addItem("SC");
        cmb_estado.addItem("SP");
        cmb_estado.addItem("SE");
        cmb_estado.addItem("TO");
        cmb_estado.setSelectedIndex(-1);
        this.setLocationRelativeTo(null);
    }
    private void limpar(){
        txt_bairro.setText("");
        txt_celular.setText("");
        txt_cidade.setText("");
        txt_comp.setText("");
        txt_cpf.setText("");
        txt_email.setText("");
        txt_endereco.setText("");
        txt_fone.setText("");
        txt_nome.setText("");
        txt_numero.setText("");
        cmb_estado.setSelectedIndex(-1);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextField();
        lbl_nome_cliente = new javax.swing.JLabel();
        lbl_cpf_cliente = new javax.swing.JLabel();
        lbl_endereco_cliente = new javax.swing.JLabel();
        lbl_tel_cliente = new javax.swing.JLabel();
        lbl_cel_cliente = new javax.swing.JLabel();
        lbl_numero_cliente = new javax.swing.JLabel();
        lbl_comp_cliente = new javax.swing.JLabel();
        lbl_bairro_cliente = new javax.swing.JLabel();
        lbl_cidade_cliente = new javax.swing.JLabel();
        lbl_estado_cliente = new javax.swing.JLabel();
        lbl_email_cliente = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        txt_comp = new javax.swing.JTextField();
        txt_cidade = new javax.swing.JTextField();
        txt_fone = new javax.swing.JTextField();
        txt_bairro = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        txt_email = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        txt_cpf = new javax.swing.JFormattedTextField();

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_nome_cliente.setText("Nome:");

        lbl_cpf_cliente.setText("CPF:");

        lbl_endereco_cliente.setText("Endereço:");

        lbl_tel_cliente.setText("Telefone:");

        lbl_cel_cliente.setText("Celular:");

        lbl_numero_cliente.setText("Número:");

        lbl_comp_cliente.setText("Complemento:");

        lbl_bairro_cliente.setText("Bairro:");

        lbl_cidade_cliente.setText("Cidade:");

        lbl_estado_cliente.setText("Estado:");

        lbl_email_cliente.setText("E-mail:");

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estadoActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_estado_cliente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nome_cliente)
                            .addComponent(lbl_cpf_cliente))
                        .addGap(36, 36, 36)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_bairro_cliente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tel_cliente)
                        .addGap(18, 18, 18)
                        .addComponent(txt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_numero_cliente)
                                .addComponent(lbl_cidade_cliente)
                                .addComponent(lbl_cel_cliente)
                                .addComponent(lbl_email_cliente))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_excluir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_limpar)
                            .addGap(18, 18, 18)
                            .addComponent(btn_cadastrar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbl_endereco_cliente)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_numero)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_comp_cliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_endereco)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome_cliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cpf_cliente)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_endereco_cliente)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numero_cliente)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_comp_cliente))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bairro_cliente)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cidade_cliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estado_cliente)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tel_cliente)
                    .addComponent(txt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cel_cliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email_cliente)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_limpar)
                    .addComponent(btn_excluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void cmb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estadoActionPerformed
      
    }//GEN-LAST:event_cmb_estadoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
          
          if(txt_nome.getText().isEmpty() || txt_bairro.getText().isEmpty() || txt_celular.getText().isEmpty() || txt_cidade.getText().isEmpty()
                  || txt_cpf.getText().isEmpty() || txt_email.getText().isEmpty() || txt_endereco.getText().isEmpty()
                  || txt_email.getText().isEmpty() || txt_fone.getText().isEmpty() || cmb_estado.getSelectedItem().toString().isEmpty()){
              JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
          
          }
          else{
          Cliente c = new Cliente();
          ClienteDAO dao = new ClienteDAO();
          c.setNome(txt_nome.getText());
          c.setBairro(txt_bairro.getText());
          c.setCelular(txt_celular.getText());
          c.setCidade(txt_cidade.getText());
          c.setComplemento(txt_comp.getText());
          c.setCpf(txt_cpf.getText());
          c.setEmail(txt_email.getText());
          c.setEndereco(txt_endereco.getText());
          c.setEstado(cmb_estado.getSelectedItem().toString());
          c.setEmail(txt_email.getText());
          c.setNumero(txt_numero.getText());
          c.setTelefone(txt_fone.getText());
          
          if(dao.verificaCliente(txt_cpf.getText())==false) 
              dao.create(c);
          else {
              dao.update(c);
          }
          limpar();
          }
             
          
          
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Isto acarretará na exclusão completa do cliente e de seus animais.\n Tem certeza que deseja excluir?");
        if(resp==JOptionPane.YES_OPTION){
        Animal a = new Animal();   
        
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
    
        try {
            stmt = con.prepareStatement("DELETE FROM tb_animal WHERE cpf=?");
            stmt.setString(1, txt_cpf.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(ClienteDAO.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao excluir."+ex);
        }finally{
            ConnectionFactory.closeConnection(con, stmt);
        }
    }
           Cliente c = new Cliente();
           ClienteDAO cdao = new ClienteDAO();
           c.setCpf(txt_cpf.getText());  
           cdao.delete(c);
           
           limpar();
        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        limpar();
    }//GEN-LAST:event_btn_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_limpar;
    public javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel lbl_bairro_cliente;
    private javax.swing.JLabel lbl_cel_cliente;
    private javax.swing.JLabel lbl_cidade_cliente;
    private javax.swing.JLabel lbl_comp_cliente;
    private javax.swing.JLabel lbl_cpf_cliente;
    private javax.swing.JLabel lbl_email_cliente;
    private javax.swing.JLabel lbl_endereco_cliente;
    private javax.swing.JLabel lbl_estado_cliente;
    private javax.swing.JLabel lbl_nome_cliente;
    private javax.swing.JLabel lbl_numero_cliente;
    private javax.swing.JLabel lbl_tel_cliente;
    public javax.swing.JTextField txt_bairro;
    public javax.swing.JTextField txt_celular;
    public javax.swing.JTextField txt_cidade;
    public javax.swing.JTextField txt_comp;
    public javax.swing.JFormattedTextField txt_cpf;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_endereco;
    public javax.swing.JTextField txt_fone;
    public javax.swing.JTextField txt_nome;
    public javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
}
