/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Admin
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Clínica veterinária");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        lbl_figura_animal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_opcoes = new javax.swing.JMenu();
        menu_animal = new javax.swing.JMenu();
        menu_item_cadastrar_animal = new javax.swing.JMenuItem();
        menu_item_pesquisar_animal = new javax.swing.JMenuItem();
        menu_cliente = new javax.swing.JMenu();
        menu_item_cadastrar_cliente = new javax.swing.JMenuItem();
        menu_item_pesquisar_cliente = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        menu_item_av_consultas = new javax.swing.JMenuItem();
        menu_realizar_consulta = new javax.swing.JMenu();
        menu_item_primaria = new javax.swing.JMenuItem();
        menu_item_retorno = new javax.swing.JMenuItem();
        menu_exames = new javax.swing.JMenu();
        menu_item_av_exames = new javax.swing.JMenuItem();
        menu_item_sol_exame = new javax.swing.JMenuItem();
        menu_tratamento = new javax.swing.JMenu();
        menu_item_registrar_tratamento = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_figura_animal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_figura_animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Animal.png"))); // NOI18N

        menu_opcoes.setText("Menu");

        menu_animal.setText("Animal");

        menu_item_cadastrar_animal.setText("Cadastrar animal");
        menu_item_cadastrar_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cadastrar_animalActionPerformed(evt);
            }
        });
        menu_animal.add(menu_item_cadastrar_animal);

        menu_item_pesquisar_animal.setText("Pesquisar animal");
        menu_item_pesquisar_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_pesquisar_animalActionPerformed(evt);
            }
        });
        menu_animal.add(menu_item_pesquisar_animal);

        menu_opcoes.add(menu_animal);

        menu_cliente.setText("Cliente");

        menu_item_cadastrar_cliente.setText("Cadastrar cliente");
        menu_item_cadastrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cadastrar_clienteActionPerformed(evt);
            }
        });
        menu_cliente.add(menu_item_cadastrar_cliente);

        menu_item_pesquisar_cliente.setText("Pesquisar cliente");
        menu_item_pesquisar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_pesquisar_clienteActionPerformed(evt);
            }
        });
        menu_cliente.add(menu_item_pesquisar_cliente);

        menu_opcoes.add(menu_cliente);

        menu_consultas.setText("Consultas");

        menu_item_av_consultas.setText("Averiguar consultas");
        menu_item_av_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_av_consultasActionPerformed(evt);
            }
        });
        menu_consultas.add(menu_item_av_consultas);

        menu_realizar_consulta.setText("Realizar consulta");

        menu_item_primaria.setText("Consulta primária");
        menu_item_primaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_primariaActionPerformed(evt);
            }
        });
        menu_realizar_consulta.add(menu_item_primaria);

        menu_item_retorno.setText("Consulta de retorno");
        menu_item_retorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_retornoActionPerformed(evt);
            }
        });
        menu_realizar_consulta.add(menu_item_retorno);

        menu_consultas.add(menu_realizar_consulta);

        menu_opcoes.add(menu_consultas);

        menu_exames.setText("Exames");

        menu_item_av_exames.setText("Averiguar exames");
        menu_item_av_exames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_av_examesActionPerformed(evt);
            }
        });
        menu_exames.add(menu_item_av_exames);

        menu_item_sol_exame.setText("Solicitar exame");
        menu_item_sol_exame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_sol_exameActionPerformed(evt);
            }
        });
        menu_exames.add(menu_item_sol_exame);

        menu_opcoes.add(menu_exames);

        menu_tratamento.setText("Tratamentos");

        menu_item_registrar_tratamento.setText("Registrar tratamento");
        menu_item_registrar_tratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_registrar_tratamentoActionPerformed(evt);
            }
        });
        menu_tratamento.add(menu_item_registrar_tratamento);

        jMenuItem2.setText("Averiguar tratamentos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_tratamento.add(jMenuItem2);

        menu_opcoes.add(menu_tratamento);

        jMenuBar1.add(menu_opcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_figura_animal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_figura_animal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cadastrar_clienteActionPerformed
         Cadastro_cliente cc = new Cadastro_cliente();
         cc.setVisible(true);
    }//GEN-LAST:event_menu_item_cadastrar_clienteActionPerformed

    private void menu_item_pesquisar_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_pesquisar_animalActionPerformed
         Pesquisa_Animal pa = new Pesquisa_Animal();
         pa.setVisible(true);
    }//GEN-LAST:event_menu_item_pesquisar_animalActionPerformed

    private void menu_item_cadastrar_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cadastrar_animalActionPerformed
        Cadastro_animal cadanimal = new Cadastro_animal();
        cadanimal.setVisible(true);
    }//GEN-LAST:event_menu_item_cadastrar_animalActionPerformed

    private void menu_item_sol_exameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_sol_exameActionPerformed
       Solicitacao_exame se = new Solicitacao_exame();
       se.setVisible(true);
    }//GEN-LAST:event_menu_item_sol_exameActionPerformed

    private void menu_item_primariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_primariaActionPerformed
        View_Primaria p = new View_Primaria();
        p.setVisible(true);
    }//GEN-LAST:event_menu_item_primariaActionPerformed

    private void menu_item_retornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_retornoActionPerformed
        View_Retorno r = new View_Retorno();
        r.setVisible(true);
    }//GEN-LAST:event_menu_item_retornoActionPerformed

    private void menu_item_pesquisar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_pesquisar_clienteActionPerformed
        Pesquisa_Cliente pc = new Pesquisa_Cliente();
        pc.setVisible(true);
    }//GEN-LAST:event_menu_item_pesquisar_clienteActionPerformed

    private void menu_item_av_examesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_av_examesActionPerformed
       Pesquisa_Exame pe = new Pesquisa_Exame();
       pe.setVisible(true);
    }//GEN-LAST:event_menu_item_av_examesActionPerformed

    private void menu_item_av_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_av_consultasActionPerformed
        Pesquisa_Primaria pc = new Pesquisa_Primaria();
        pc.setVisible(true);
    }//GEN-LAST:event_menu_item_av_consultasActionPerformed

    private void menu_item_registrar_tratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_registrar_tratamentoActionPerformed
        Registro_Tratamento rt = new Registro_Tratamento();
        rt.setVisible(true);
    }//GEN-LAST:event_menu_item_registrar_tratamentoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Pesquisa_Tratamento pt = new Pesquisa_Tratamento();
       pt.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbl_figura_animal;
    private javax.swing.JMenu menu_animal;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_exames;
    private javax.swing.JMenuItem menu_item_av_consultas;
    private javax.swing.JMenuItem menu_item_av_exames;
    private javax.swing.JMenuItem menu_item_cadastrar_animal;
    private javax.swing.JMenuItem menu_item_cadastrar_cliente;
    private javax.swing.JMenuItem menu_item_pesquisar_animal;
    private javax.swing.JMenuItem menu_item_pesquisar_cliente;
    private javax.swing.JMenuItem menu_item_primaria;
    private javax.swing.JMenuItem menu_item_registrar_tratamento;
    private javax.swing.JMenuItem menu_item_retorno;
    private javax.swing.JMenuItem menu_item_sol_exame;
    private javax.swing.JMenu menu_opcoes;
    private javax.swing.JMenu menu_realizar_consulta;
    private javax.swing.JMenu menu_tratamento;
    // End of variables declaration//GEN-END:variables
}
