/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.dao.ClienteDAO;
import model.dao.ConsultaDAO;
import model.dao.ExameDAO;
import Classes_back.Cliente;
import Classes_back.Exame;


/**
 *
 * @author Admin
 */
public class Marcacao_consulta extends javax.swing.JFrame {

    /**
     * Creates new form Marcacao_consulta
     */
    public Marcacao_consulta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    protected void limpar(){
        txt_cpf.setText("");
        cmb_nome_animal.removeAllItems();
        txt_nome_cliente.setText("");
        txt_sintomas.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbl_nome_do_cliente = new javax.swing.JLabel();
        lbl_nome_do_animal = new javax.swing.JLabel();
        txt_nome_cliente = new javax.swing.JTextField();
        lbl_cpf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_sintomas = new javax.swing.JTextArea();
        lbl_sintomas = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_solicitar = new javax.swing.JButton();
        btn_exames_solicitados = new javax.swing.JButton();
        txt_cpf = new javax.swing.JFormattedTextField();
        cmb_nome_animal = new javax.swing.JComboBox<>();

        lbl_nome_do_cliente.setText("Nome do cliente:");

        lbl_nome_do_animal.setText("Nome do animal:");

        lbl_cpf.setText("CPF do cliente:");

        txt_sintomas.setColumns(20);
        txt_sintomas.setRows(5);
        jScrollPane1.setViewportView(txt_sintomas);

        lbl_sintomas.setText("Sintomas:");

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_solicitar.setText("Solicitar Exame");
        btn_solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarActionPerformed(evt);
            }
        });

        btn_exames_solicitados.setText("Exames solicitados");
        btn_exames_solicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exames_solicitadosActionPerformed(evt);
            }
        });

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpfFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_solicitar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_limpar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_registrar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_nome_do_animal)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmb_nome_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(btn_exames_solicitados))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_cpf)
                                    .addComponent(lbl_nome_do_cliente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nome_cliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_sintomas)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpf)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome_do_cliente)
                    .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome_do_animal)
                    .addComponent(btn_exames_solicitados)
                    .addComponent(cmb_nome_animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sintomas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrar)
                    .addComponent(btn_limpar)
                    .addComponent(btn_solicitar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
       cadastrar();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarActionPerformed
        solicitarExame();
    }//GEN-LAST:event_btn_solicitarActionPerformed

    private void btn_exames_solicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exames_solicitadosActionPerformed
        Exame e = new Exame();
        ExameDAO edao = new ExameDAO();
        Pesquisa_Exame pe = new Pesquisa_Exame();
        pe.setVisible(true);
        pe.readTabelaPesquisaAnimal(cmb_nome_animal.getSelectedItem().toString());
    }//GEN-LAST:event_btn_exames_solicitadosActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        limpar();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void txt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusLost
        ClienteDAO cdao = new ClienteDAO();
        Cliente c = new Cliente();
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt=null;
        ResultSet rs = null;
        if(cdao.verificaCliente(txt_cpf.getText())==true){
          try {
              stmt = con.prepareStatement("SELECT cliente, animal FROM tb_animal WHERE cpf=?");
              stmt.setString(1, txt_cpf.getText());
              rs=stmt.executeQuery();
              while(rs.next()){
                 txt_nome_cliente.setText(rs.getString("cliente"));
                 cmb_nome_animal.addItem(rs.getString("animal"));
              }

          } catch (SQLException ex) {
              Logger.getLogger(Cadastro_animal.class.getName()).log(Level.SEVERE, null, ex);
         }
        }     
    }//GEN-LAST:event_txt_cpfFocusLost

    private void txt_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusGained
         limpar();
    }//GEN-LAST:event_txt_cpfFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcacao_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcacao_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcacao_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcacao_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marcacao_consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btn_exames_solicitados;
    protected javax.swing.JButton btn_limpar;
    protected javax.swing.JButton btn_registrar;
    protected javax.swing.JButton btn_solicitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    protected javax.swing.JComboBox<String> cmb_nome_animal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_nome_do_animal;
    private javax.swing.JLabel lbl_nome_do_cliente;
    private javax.swing.JLabel lbl_sintomas;
    protected javax.swing.JFormattedTextField txt_cpf;
    protected javax.swing.JTextField txt_nome_cliente;
    protected javax.swing.JTextArea txt_sintomas;
    // End of variables declaration//GEN-END:variables
protected void cadastrar(){
    //btn_registrar.getAccessibleContext();
    JOptionPane.showMessageDialog(this, "Dados registrados com sucesso.");
}
    protected void solicitarExame(){
       ConsultaDAO rdao = new ConsultaDAO();
        if(rdao.verificaCliente(txt_cpf.getText())==true){
            Solicitacao_exame se = new Solicitacao_exame();
            se.setVisible(true);
            se.txt_cpf.setText(txt_cpf.getText());
            se.cmb_nome_animal.setSelectedItem(cmb_nome_animal.getSelectedItem());
            se.txt_nome_cliente.setText(txt_nome_cliente.getText());
        }
        else{
           JOptionPane.showMessageDialog(this, "Cliente não cadastrado!");
           Cadastro_cliente cc = new Cadastro_cliente();
           cc.setVisible(true);
           cc.txt_cpf.setText(txt_cpf.getText());
        }
    }
}

