/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.dao.ExameDAO;
import Classes_back.Exame;

/**
 *
 * @author Admin
 */
public class Pesquisa_Exame extends javax.swing.JFrame {

   
    private int parametro; 
    
    public Pesquisa_Exame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Pesquisa de exames");
    }
    
    public void readTabelaPesquisaCliente(String busca){
        DefaultTableModel tb = (DefaultTableModel) j_tb_exame.getModel();
        tb.setNumRows(0);
        ExameDAO ed = new ExameDAO();
        
        for(Exame e: ed.readPesquisaCliente(busca)){
            tb.addRow(new Object[]{e.getId(),e.getNome_cliente(),e.getCpf_cliente(),e.getNome_animal(),e.getEspecie(),e.getSuspeita(),
            e.isTratamento(),e.getTipo_ratamento(),e.getCategoria_exame(),e.getTipo_exame()});
        }
    }
    public void readTabelaPesquisaCPF(String busca){
        DefaultTableModel tb = (DefaultTableModel) j_tb_exame.getModel();
        tb.setNumRows(0);
        ExameDAO ed = new ExameDAO();
        
        for(Exame e: ed.readPesquisaCPF(busca)){
            tb.addRow(new Object[]{e.getId(),e.getNome_cliente(),e.getCpf_cliente(),e.getNome_animal(),e.getEspecie(),e.getSuspeita(),
            e.isTratamento(),e.getTipo_ratamento(),e.getCategoria_exame(),e.getTipo_exame()});
        }
    }
    public void readTabelaPesquisaAnimal(String busca){
        DefaultTableModel tb = (DefaultTableModel) j_tb_exame.getModel();
        tb.setNumRows(0);
        ExameDAO ed = new ExameDAO();
        
        for(Exame e: ed.readPesquisaAnimal(busca)){
            tb.addRow(new Object[]{e.getId(),e.getNome_cliente(),e.getCpf_cliente(),e.getNome_animal(),e.getEspecie(),e.getSuspeita(),
            e.isTratamento(),e.getTipo_ratamento(),e.getCategoria_exame(),e.getTipo_exame()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_tb_exame = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rbt_cliente = new javax.swing.JRadioButton();
        rbt_animal = new javax.swing.JRadioButton();
        rbt_cpf = new javax.swing.JRadioButton();
        txt_pesquisa = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();

        j_tb_exame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "CPF", "Animal", "Espécie", "Suspeita", "Tratamento", "Tipo de tratamneto", "Categoria de exame", "Tipo de exame"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        j_tb_exame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_tb_exameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(j_tb_exame);

        jLabel1.setText("Pesquisar por:");

        buttonGroup1.add(rbt_cliente);
        rbt_cliente.setText("Nome do cliente");

        buttonGroup1.add(rbt_animal);
        rbt_animal.setText("Animal");

        buttonGroup1.add(rbt_cpf);
        rbt_cpf.setText("CPF");

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbt_cliente)
                .addGap(18, 18, 18)
                .addComponent(rbt_animal)
                .addGap(18, 18, 18)
                .addComponent(rbt_cpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pesquisa))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_excluir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbt_cliente)
                    .addComponent(rbt_animal)
                    .addComponent(rbt_cpf)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_pesquisar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_excluir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_tb_exameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_tb_exameMouseClicked
        parametro=Integer.parseInt(j_tb_exame.getValueAt(j_tb_exame.getSelectedRow(), 0).toString());
        
    }//GEN-LAST:event_j_tb_exameMouseClicked

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Exame e = new Exame();
        ExameDAO ed = new ExameDAO();
        e.setId(parametro);
        ed.delete(e);
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        if(rbt_animal.isSelected() || rbt_cliente.isSelected() || rbt_cpf.isSelected()){
           if(rbt_cliente.isSelected())
               readTabelaPesquisaCliente(txt_pesquisa.getText());
           if(rbt_animal.isSelected())
               readTabelaPesquisaAnimal(txt_pesquisa.getText());
           if(rbt_cpf.isSelected())
               readTabelaPesquisaCPF(txt_pesquisa.getText());
        }
        else
            readTabelaPesquisaCliente(txt_pesquisa.getText());
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa_Exame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_tb_exame;
    private javax.swing.JRadioButton rbt_animal;
    private javax.swing.JRadioButton rbt_cliente;
    private javax.swing.JRadioButton rbt_cpf;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
