/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.ClienteDAO;
import Classes_back.Cliente;

/**
 *
 * @author Admin
 */
public class Pesquisa_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisa_Cliente
     */
    public Pesquisa_Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Pesquisa de clientes");
        DefaultTableModel tb = (DefaultTableModel) j_tb_cliente.getModel();
        j_tb_cliente.setRowSorter(new TableRowSorter(tb));
    }
    
    public void readTabelaPesquisaNome(String busca){
        DefaultTableModel tb = (DefaultTableModel) j_tb_cliente.getModel();
        tb.setNumRows(0);
        ClienteDAO cd = new ClienteDAO();
        
        for(Cliente c: cd.readPesquisaNome(busca)){
            tb.addRow(new Object[]{c.getNome(), c.getCpf(), c.getEndereco(), c.getNumero(),c.getComplemento(),
            c.getBairro(),c.getCidade(),c.getEstado(),c.getTelefone(),c.getCelular(),c.getEmail()});
        }
    }
    
    public void readTabelaPesquisaCPF(String busca){
        DefaultTableModel tb = (DefaultTableModel) j_tb_cliente.getModel();
        tb.setNumRows(0);
        ClienteDAO cd = new ClienteDAO();
        
        for(Cliente c: cd.readPesquisaCPF(busca)){
            tb.addRow(new Object[]{c.getNome(), c.getCpf(), c.getEndereco(), c.getNumero(),c.getComplemento(),
            c.getBairro(),c.getCidade(),c.getEstado(),c.getTelefone(),c.getCelular(),c.getEmail()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_tb_cliente = new javax.swing.JTable();
        rbt_nome = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rbt_cpf = new javax.swing.JRadioButton();
        txt_pesquisa = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();

        j_tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Endereço", "Nº", "Complemento", "Bairro", "Cidade", "estado", "Telefone", "Celular", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        j_tb_cliente.getTableHeader().setReorderingAllowed(false);
        j_tb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_tb_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(j_tb_cliente);

        buttonGroup1.add(rbt_nome);
        rbt_nome.setText("Nome");

        jLabel1.setText("Pesquisar por:");

        buttonGroup1.add(rbt_cpf);
        rbt_cpf.setText("CPF");
        rbt_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_cpfActionPerformed(evt);
            }
        });

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_pesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt_cpf)
                    .addComponent(rbt_nome)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btn_pesquisar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_cpfActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        if(rbt_nome.isSelected() || rbt_cpf.isSelected()){
           if(rbt_nome.isSelected())
               readTabelaPesquisaNome(txt_pesquisa.getText());
           if(rbt_cpf.isSelected())
               readTabelaPesquisaCPF(txt_pesquisa.getText());
        }
        else
             readTabelaPesquisaNome(txt_pesquisa.getText());
           // JOptionPane.showMessageDialog(this, "Favor selecionar o tipo de pesquisa.");
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void j_tb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_tb_clienteMouseClicked
        if(j_tb_cliente.getSelectedRow() != -1){
            Cadastro_cliente cc = new Cadastro_cliente();
            cc.setVisible(true);
            cc.txt_nome.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 0).toString());
            cc.txt_cpf.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 1).toString());
            cc.txt_endereco.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 2).toString());
            cc.txt_numero.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 3).toString());
            cc.txt_comp.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 4).toString());
            cc.txt_bairro.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 5).toString());
            cc.txt_cidade.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 6).toString());
            cc.cmb_estado.setSelectedItem(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 7));
            cc.txt_fone.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 8).toString());
            cc.txt_celular.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 9).toString());
            cc.txt_email.setText(j_tb_cliente.getValueAt(j_tb_cliente.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_j_tb_clienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_tb_cliente;
    private javax.swing.JRadioButton rbt_cpf;
    private javax.swing.JRadioButton rbt_nome;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
