/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.AnimalDAO;
import model.dao.ClienteDAO;
import model.dao.ExameDAO;
import Classes_back.Animal;
import Classes_back.Cliente;
import Classes_back.Exame;

/**
 *
 * @author Admin
 */
public class Solicitacao_exame extends javax.swing.JFrame {
    /**
     * Creates new form Solicitacao_exame
     */
    public Solicitacao_exame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Solicitação de exames");
        txt_especie_outros.setEnabled(false);
        lbl_qual.setEnabled(false);
        txt_qual.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_nome_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbt_cao = new javax.swing.JRadioButton();
        rbt_gato = new javax.swing.JRadioButton();
        rbt_outros = new javax.swing.JRadioButton();
        txt_especie_outros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_suspeita = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbt_sim = new javax.swing.JRadioButton();
        rbt_nao = new javax.swing.JRadioButton();
        lbl_qual = new javax.swing.JLabel();
        txt_qual = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbt_bioquimicos = new javax.swing.JRadioButton();
        rbt_hematologia = new javax.swing.JRadioButton();
        rbt_parasitologia = new javax.swing.JRadioButton();
        rbt_microbiologia = new javax.swing.JRadioButton();
        rbt_virus = new javax.swing.JRadioButton();
        rbt_hormonios = new javax.swing.JRadioButton();
        rbt_medicamentos = new javax.swing.JRadioButton();
        rbt_urinalise = new javax.swing.JRadioButton();
        rbt_coagulacao = new javax.swing.JRadioButton();
        cmb_exame = new javax.swing.JComboBox<>();
        btn_solicitar_exame = new javax.swing.JButton();
        txt_cpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_nome_animal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Nome do cliente:");

        jLabel3.setText("Espécie");

        buttonGroup1.add(rbt_cao);
        rbt_cao.setText("Cão");
        rbt_cao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_caoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbt_gato);
        rbt_gato.setText("Gato");
        rbt_gato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_gatoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbt_outros);
        rbt_outros.setText("Outros");
        rbt_outros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_outrosActionPerformed(evt);
            }
        });

        jLabel4.setText("Suspeita clínica:");

        jLabel5.setText("Animal em tratamento?");

        buttonGroup2.add(rbt_sim);
        rbt_sim.setText("Sim");
        rbt_sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_simActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbt_nao);
        rbt_nao.setText("Não");
        rbt_nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_naoActionPerformed(evt);
            }
        });

        lbl_qual.setText("Qual?");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exames"));

        buttonGroup3.add(rbt_bioquimicos);
        rbt_bioquimicos.setText("Bioquímicos");
        rbt_bioquimicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_bioquimicosActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_hematologia);
        rbt_hematologia.setText("Hematologia");
        rbt_hematologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_hematologiaActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_parasitologia);
        rbt_parasitologia.setText("Parasitologia");
        rbt_parasitologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_parasitologiaActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_microbiologia);
        rbt_microbiologia.setText("Microbiologia");
        rbt_microbiologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_microbiologiaActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_virus);
        rbt_virus.setText("Pesquisa de vírus");
        rbt_virus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_virusActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_hormonios);
        rbt_hormonios.setText("Hormônios");
        rbt_hormonios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_hormoniosActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_medicamentos);
        rbt_medicamentos.setText("Medicamentos");
        rbt_medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_medicamentosActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_urinalise);
        rbt_urinalise.setText("Urinálise");
        rbt_urinalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_urinaliseActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbt_coagulacao);
        rbt_coagulacao.setText("Coagulação");
        rbt_coagulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_coagulacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbt_bioquimicos)
                        .addGap(33, 33, 33)
                        .addComponent(rbt_hematologia)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbt_virus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbt_hormonios)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rbt_parasitologia)
                        .addGap(55, 55, 55)
                        .addComponent(rbt_medicamentos)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbt_coagulacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(rbt_urinalise)
                        .addGap(38, 38, 38)
                        .addComponent(rbt_microbiologia)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_bioquimicos)
                    .addComponent(rbt_hematologia)
                    .addComponent(rbt_microbiologia)
                    .addComponent(rbt_urinalise)
                    .addComponent(rbt_coagulacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_virus)
                    .addComponent(rbt_hormonios)
                    .addComponent(rbt_medicamentos)
                    .addComponent(rbt_parasitologia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmb_exame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_exameActionPerformed(evt);
            }
        });

        btn_solicitar_exame.setText("Solicitar exame");
        btn_solicitar_exame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitar_exameActionPerformed(evt);
            }
        });

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpfFocusLost(evt);
            }
        });

        jLabel6.setText("CPF do cliente:");

        cmb_nome_animal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_nome_animalMouseClicked(evt);
            }
        });
        cmb_nome_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_nome_animalActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do animal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_sim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_nao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_qual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_qual))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_solicitar_exame))
                    .addComponent(cmb_exame, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbt_cao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbt_gato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_outros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_especie_outros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_suspeita))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_nome_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_nome_animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbt_cao)
                    .addComponent(rbt_gato)
                    .addComponent(rbt_outros)
                    .addComponent(txt_especie_outros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_suspeita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbt_sim)
                    .addComponent(rbt_nao)
                    .addComponent(lbl_qual)
                    .addComponent(txt_qual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmb_exame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_solicitar_exame)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_simActionPerformed
        lbl_qual.setEnabled(true);
        txt_qual.setEnabled(true);
    }//GEN-LAST:event_rbt_simActionPerformed

    private void cmb_exameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_exameActionPerformed

    }//GEN-LAST:event_cmb_exameActionPerformed

    private void rbt_bioquimicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_bioquimicosActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Glicose");
              cmb_exame.addItem("Uréia");
              cmb_exame.addItem("Creatinina");
              cmb_exame.addItem("CPK");
              cmb_exame.addItem("Fosfatase Alcalina");
              cmb_exame.addItem("TGO");
              cmb_exame.addItem("TGP");
              cmb_exame.addItem("Gama GT");
              cmb_exame.addItem("Bilirrubina Total");
              cmb_exame.addItem("Bilirrubina Direta");
              cmb_exame.addItem("Bilirrubina Indireta");
              cmb_exame.addItem("Proteínas totais");
              cmb_exame.addItem("Albumina");
              cmb_exame.addItem("Globulina");
              cmb_exame.addItem("Outros");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_bioquimicosActionPerformed

    private void rbt_hematologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_hematologiaActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Hemograma com plaquetas + PPT");
              cmb_exame.addItem("Pesquisa de Hematozoários");
              cmb_exame.addItem("Outros");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_hematologiaActionPerformed

    private void rbt_coagulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_coagulacaoActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Tempo de Protrombina - T");
              cmb_exame.addItem("Tempo de Tromboplastina Parcial Ativada -TTPA");
              cmb_exame.addItem("Plaquetas");
              cmb_exame.addItem("Fibrinogênio");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_coagulacaoActionPerformed

    private void rbt_urinaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_urinaliseActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Urina tipo I");
              cmb_exame.addItem("Outros");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_urinaliseActionPerformed

    private void rbt_microbiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_microbiologiaActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Cultura para bactérias");
              cmb_exame.addItem("Cultura para fungos");
              cmb_exame.addItem("Micológico direto");
              cmb_exame.addItem("Urinocultura");
              cmb_exame.addItem("Hemocultura");
              cmb_exame.addItem("Antibiograma");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_microbiologiaActionPerformed

    private void rbt_virusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_virusActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Pesquisa de Rotavírus nas fezes");
              cmb_exame.addItem("Pesquisa de Parvovírus nas fezes");
              cmb_exame.addItem("Pesquisa de Cinomose em secreção nasal ou ocular, soro ou plasma, urina");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_virusActionPerformed

    private void rbt_hormoniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_hormoniosActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("TSH");
              cmb_exame.addItem("T4");
              cmb_exame.addItem("T4L");
              cmb_exame.addItem("T3");
              cmb_exame.addItem("Cortisol");
              cmb_exame.addItem("PTH");
              cmb_exame.addItem("Progesterona");
              cmb_exame.addItem("Testosterona");
              cmb_exame.addItem("Outros");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_hormoniosActionPerformed

    private void rbt_parasitologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_parasitologiaActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Parasitológico de fezes");
              cmb_exame.addItem("Pesquisa de ácaros");
              cmb_exame.addItem("Pesquisa de sangue oculto nas fezes");
              cmb_exame.addItem("Outros");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_parasitologiaActionPerformed

    private void rbt_medicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_medicamentosActionPerformed
              cmb_exame.removeAllItems();
              cmb_exame.addItem("Digoxina");
              cmb_exame.addItem("Fenitoína");
              cmb_exame.addItem("Fenobarbital");
              cmb_exame.setSelectedIndex(-1);
    }//GEN-LAST:event_rbt_medicamentosActionPerformed

    private void rbt_caoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_caoActionPerformed
        txt_especie_outros.setEnabled(false);
    }//GEN-LAST:event_rbt_caoActionPerformed

    private void rbt_outrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_outrosActionPerformed
        txt_especie_outros.setEnabled(true);
    }//GEN-LAST:event_rbt_outrosActionPerformed

    private void rbt_gatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_gatoActionPerformed
        txt_especie_outros.setEnabled(false);
    }//GEN-LAST:event_rbt_gatoActionPerformed

    private void rbt_naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_naoActionPerformed
       lbl_qual.setEnabled(false);
       txt_qual.setEnabled(false);
    }//GEN-LAST:event_rbt_naoActionPerformed

    private void btn_solicitar_exameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitar_exameActionPerformed
        Exame e = new Exame();
        ExameDAO edao = new ExameDAO();
        String cat_exame=null;
        String especie=null;
        boolean tratamento=false;
        if (rbt_bioquimicos.isSelected())
            cat_exame="Bioqímicos";
        if(rbt_coagulacao.isSelected())
            cat_exame="Coagulação";
        if (rbt_hematologia.isSelected())
            cat_exame="Hematologia";
        if(rbt_hormonios.isSelected())
            cat_exame="Hormônios";
        if (rbt_medicamentos.isSelected())
            cat_exame="Medicamentos";
        if(rbt_microbiologia.isSelected())
            cat_exame="Microbiologia";
        if (rbt_parasitologia.isSelected())
            cat_exame="Parasitologia";
        if(rbt_urinalise.isSelected())
            cat_exame="Urinálise";
        if(rbt_virus.isSelected())
            cat_exame="Vírus";
        if (rbt_cao.isSelected())
            especie="Cão";
        if(rbt_gato.isSelected())
            especie="Gato";
        if (rbt_outros.isSelected())
            especie=txt_especie_outros.getText();
        if(rbt_sim.isSelected())
            tratamento=true;
        if(rbt_nao.isSelected())
            tratamento=false;
        
        
        int index;
        index=cmb_exame.getSelectedIndex();
        if(index==-1)
           JOptionPane.showMessageDialog(this, "Favor escolher um tipo de exame.");
        if(edao.verificaExame(txt_cpf.getText())==true){
            e.setCategoria_exame(cat_exame);
            e.setEspecie(especie);
            e.setNome_animal(cmb_nome_animal.getSelectedItem().toString());
            e.setNome_cliente(txt_nome_cliente.getText());
            e.setCpf_cliente(txt_cpf.getText());
            e.setSuspeita(txt_suspeita.getText());
            e.setTipo_exame(cmb_exame.getSelectedItem().toString());
            e.setTipo_ratamento(txt_qual.getText());
            e.setTratamento(tratamento);
            edao.create(e);
           int resp = JOptionPane.showConfirmDialog(this, "Deseja solicitar outro exame?");
           if(resp==JOptionPane.NO_OPTION)
               hide();
        }
        else{
           JOptionPane.showMessageDialog(this, "Cliente não cadastrado!");
           Cadastro_cliente cc = new Cadastro_cliente();
           cc.setVisible(true);
           cc.txt_cpf.setText(txt_cpf.getText());
        }
                
    }//GEN-LAST:event_btn_solicitar_exameActionPerformed

    private void txt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusLost
        ExameDAO edao = new ExameDAO();
        Cliente c = new Cliente();
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt=null;
        ResultSet rs = null;
        if(edao.verificaExame(txt_cpf.getText())==true){
          try {
              stmt = con.prepareStatement("SELECT cliente, animal FROM tb_animal WHERE cpf=?");
              stmt.setString(1, txt_cpf.getText());
              rs=stmt.executeQuery();
              while(rs.next()){
                 txt_nome_cliente.setText(rs.getString("cliente"));
                 cmb_nome_animal.addItem(rs.getString("animal"));
              }

          } catch (SQLException ex) {
              Logger.getLogger(Cadastro_animal.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
    }//GEN-LAST:event_txt_cpfFocusLost

    private void txt_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusGained
       cmb_nome_animal.removeAllItems();
       cmb_nome_animal.setSelectedItem("");
       txt_nome_cliente.setText("");
       txt_suspeita.setText("");
       txt_especie_outros.setText("");
       txt_qual.setText("");
       rbt_bioquimicos.setSelected(false);
       rbt_cao.setSelected(false);
       rbt_coagulacao.setSelected(false);
       rbt_gato.setSelected(false);
       rbt_hematologia.setSelected(false);
       rbt_hormonios.setSelected(false);
       rbt_medicamentos.setSelected(false);
       rbt_microbiologia.setSelected(false);
       rbt_nao.setSelected(false);
       rbt_outros.setSelected(false);
       rbt_parasitologia.setSelected(false);
       rbt_sim.setSelected(false);
       rbt_urinalise.setSelected(false);
       rbt_virus.setSelected(false);
       cmb_exame.setSelectedIndex(-1);
       
       //txt_cpf.setText("");
       
    }//GEN-LAST:event_txt_cpfFocusGained

    private void cmb_nome_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_nome_animalActionPerformed

        ExameDAO edao = new ExameDAO();
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt=null;
        ResultSet rs = null;
        if(edao.verificaExame(txt_cpf.getText())==true){
          try {
              if(cmb_nome_animal.getSelectedItem()!=null){
              stmt = con.prepareStatement("SELECT cliente, animal, especie FROM tb_animal WHERE cpf=? and animal=?");
              stmt.setString(1, txt_cpf.getText());
              stmt.setString(2, cmb_nome_animal.getSelectedItem().toString());
              rs=stmt.executeQuery();
              while(rs.next()){
                 if(rs.getString("especie").equals("Cão") ||rs.getString("especie").equals("Gato")){
                      if(rs.getString("especie").equals("Cão"))
                          rbt_cao.setSelected(true);
                      if(rs.getString("especie").equals("Gato"))
                          rbt_gato.setSelected(true);
                 }
                 else{
                     rbt_outros.setSelected(true);
                     txt_especie_outros.setText(rs.getString("especie"));
                 }
              }
              }
          } catch (SQLException ex) {
              Logger.getLogger(Cadastro_animal.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
       
    }//GEN-LAST:event_cmb_nome_animalActionPerformed

    private void cmb_nome_animalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_nome_animalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_nome_animalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitacao_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitacao_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitacao_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitacao_exame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solicitacao_exame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_solicitar_exame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmb_exame;
    public javax.swing.JComboBox<String> cmb_nome_animal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_qual;
    private javax.swing.JRadioButton rbt_bioquimicos;
    private javax.swing.JRadioButton rbt_cao;
    private javax.swing.JRadioButton rbt_coagulacao;
    private javax.swing.JRadioButton rbt_gato;
    private javax.swing.JRadioButton rbt_hematologia;
    private javax.swing.JRadioButton rbt_hormonios;
    private javax.swing.JRadioButton rbt_medicamentos;
    private javax.swing.JRadioButton rbt_microbiologia;
    private javax.swing.JRadioButton rbt_nao;
    private javax.swing.JRadioButton rbt_outros;
    private javax.swing.JRadioButton rbt_parasitologia;
    private javax.swing.JRadioButton rbt_sim;
    private javax.swing.JRadioButton rbt_urinalise;
    private javax.swing.JRadioButton rbt_virus;
    public javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_especie_outros;
    public javax.swing.JTextField txt_nome_cliente;
    private javax.swing.JTextField txt_qual;
    private javax.swing.JTextField txt_suspeita;
    // End of variables declaration//GEN-END:variables
}
